import { BrandMark } from './BrandMark'

export function TermsPage() {
  return (
    <div className="site-shell">
      <a className="skip-link" href="#terms-main">Skip to main content</a>
      <header className="site-header"><a className="brand-link" href="./index.html" aria-label="Return to Noitis home"><BrandMark compact /></a><nav className="privacy-nav" aria-label="Legal navigation"><a href="./index.html">Home</a><a href="./privacy.html">Privacy</a><a href="./trademark.html">Trademarks</a></nav></header>
      <main className="privacy-page" id="terms-main">
        <header className="privacy-hero"><p className="eyebrow">Noitis™ terms of use</p><h1>Clear terms for a public website.</h1><p className="privacy-hero__lead">These terms govern use of the public Noitis website and explain the boundaries around its content, product information, intellectual property, and permitted use.</p><p className="privacy-meta"><strong>Effective date:</strong> 25 August 2026</p></header>
        <section className="privacy-section"><h2>1. About the website</h2><p>The Noitis website is an informational company and product-discovery surface operated under the Noitis™ brand from Greece. It is not itself a production product service, customer account system, payment service, or contractual offer.</p><p>No separate registered Noitis legal entity is represented by these terms at this stage. If the responsible legal identity changes, the terms will be updated.</p></section>
        <section className="privacy-section"><h2>2. Product information</h2><p>Noitis products shown on the website are currently identified as <strong>In development</strong>. Descriptions are intended to reflect the current product repositories conservatively. Planned capabilities, roadmap items, production integrations, prices, public destinations, and release dates may change.</p><p>A product or pricing link is shown only when a public destination is explicitly configured for the production website. The absence of a link does not imply that a product has been launched.</p></section>
        <section className="privacy-section"><h2>3. Intellectual property</h2><p>Except for third-party materials governed by their own terms, the website&apos;s source code, text, visual design, logos, graphics, product descriptions, documentation, layouts, and other materials are owned by Noitis or their applicable rights holders.</p><p>Public access to the website or repository does not place those materials in the public domain and does not grant an open-source or commercial-use license. Repository source/content are governed by the proprietary LICENSE; Noitis brand identifiers are governed by the Trademark Policy.</p></section>
        <section className="privacy-section"><h2>4. Permitted and prohibited use</h2><p>You may browse and use the website for its intended informational purpose and make lawful references to Noitis and its products.</p><ul><li>Do not impersonate Noitis or falsely suggest affiliation, sponsorship, endorsement, or certification.</li><li>Do not misuse Noitis names, logos, marks, visual identity, or product identities.</li><li>Do not unlawfully copy, redistribute, rebrand, sell, sublicense, or commercially exploit protected materials.</li><li>Do not interfere with, attack, or attempt unauthorized access to website or linked infrastructure.</li><li>Do not remove or alter legal, ownership, copyright, or trademark notices.</li></ul></section>
        <section className="privacy-section"><h2>5. No commercial commitment</h2><p>Unless Noitis expressly agrees otherwise in a signed written agreement, website content does not create a warranty, service-level commitment, purchase obligation, investment representation, employment offer, partnership, or promise that a feature, product, release, price, or date will become available.</p></section>
        <section className="privacy-section"><h2>6. External and product links</h2><p>Configured product or third-party destinations may have separate terms, privacy notices, security controls, and availability. Noitis is not responsible for third-party content or practices merely because the website links to them.</p></section>
        <section className="privacy-section"><h2>7. Privacy</h2><p>The current website privacy practices are described on the <a href="./privacy.html">Privacy</a> page.</p></section>
        <section className="privacy-section"><h2>8. No warranty</h2><p>To the maximum extent permitted by applicable law, the website and its content are provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, except rights or warranties that cannot lawfully be excluded.</p></section>
        <section className="privacy-section"><h2>9. Limitation of liability</h2><p>To the maximum extent permitted by applicable law, Noitis and its applicable owners, contributors, affiliates, or authorized representatives shall not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages arising from the website or its content. Nothing in these terms limits liability where applicable law does not permit that limitation.</p></section>
        <section className="privacy-section"><h2>10. Changes</h2><p>Noitis may update the website and these terms as products, infrastructure, organization, or legal requirements evolve. Material revisions will be reflected by an updated effective date.</p></section>
        <section className="privacy-section"><h2>11. Applicable law</h2><p>Where a choice of law is legally permitted and no different written agreement applies, these terms are governed by the laws of Greece, without limiting mandatory rights under another applicable legal regime.</p></section>
        <section className="privacy-section"><h2>12. Contact</h2><p>Questions about these terms or requests for permission concerning website materials may be sent to:</p><p><strong>chouliarasmatthaios@gmail.com</strong></p></section>
      </main>
      <footer className="site-footer site-footer--privacy"><div className="site-footer__brand"><BrandMark /><p>Intelligence, engineered.</p></div><div className="site-footer__links"><a href="./index.html">Home</a><a href="./privacy.html">Privacy</a><a href="./terms.html">Terms</a><a href="./trademark.html">Trademarks</a></div><p className="site-footer__legal">© {new Date().getFullYear()} Noitis™. All rights reserved.</p></footer>
    </div>
  )
}
